= BriefLZ for Lua
Jakub Jirutka <https://github.com/jirutka[@jirutka]>
// custom
:name: brieflz
:repo-name: brieflz.lua
:gh-name: jirutka/{repo-name}
:gh-branch: master
:appveyor-id: jwnh6vo4hpqcb2a5
:ldoc-url: https://jirutka.github.io/{repo-name}/ldoc/

ifdef::env-github[]
image:https://travis-ci.org/{gh-name}.svg?branch={gh-branch}["Build Status", link="https://travis-ci.org/{gh-name}"]
image:https://ci.appveyor.com/api/projects/status/{appveyor-id}/branch/{gh-branch}?svg=true["Windows Build Status", link="https://ci.appveyor.com/project/jirutka/brieflz-lua"]
image:https://img.shields.io/badge/ldoc-docs-blue.svg["LDoc", link="{ldoc-url}"]
endif::env-github[]


This is a Lua binding for https://github.com/jibsen/brieflz[BriefLZ] – a small and fast open source implementation of a Lempel-Ziv style compression algorithm by Joergen Ibsen.


== Installation

You can install BriefLZ using https://luarocks.org[LuaRocks] (the Lua package manager):

[source, subs="+attributes"]
luarocks install {name}

or to get the latest development version:

[source, subs="+attributes"]
luarocks install --server=http://luarocks.org/dev {name}

Note: If you want to bootstrap development environment for running tests, read the next section.


== Set up development environment

. Clone this repository:
[source, sh, subs="+attributes"]
git clone https://github.com/{gh-name}.git
cd {repo-name}

. Install Lua and modules for running tests into directory `.venv`:

    ./script/bootstrap

. Start hacking!

//^

* Build native extension:

    ./script/build

* Run tests and linter:

    ./script/test


== License

This project is licensed under https://opensource.org/licenses/Zlib/[zlib License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
