#!/bin/sh
# vim: set ts=4:
#
# Compiles native code.
#
set -eu

. "$(dirname "$0")/bootstrap"

case "$HOST_OS" in
	Linux) CFLAGS="-std=c99 -Os -fPIC";;
esac

einfo 'Building rock'
luarocks make ${CFLAGS:+"CFLAGS=$CFLAGS"} *.rockspec
